// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenHands.OpenApiClient.Api.V1.Conversation.Item.Events;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Api.V1.Conversation.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\conversation\{conversationId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithConversationItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The events property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Api.V1.Conversation.Item.Events.EventsRequestBuilder Events
        {
            get => new global::Soenneker.OpenHands.OpenApiClient.Api.V1.Conversation.Item.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.V1.Conversation.Item.WithConversationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConversationItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/conversation/{conversationId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.V1.Conversation.Item.WithConversationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConversationItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/conversation/{conversationId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
