// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenHands.OpenApiClient.Api.V1.Users.GitInfo;
using Soenneker.OpenHands.OpenApiClient.Api.V1.Users.GitOrganizations;
using Soenneker.OpenHands.OpenApiClient.Api.V1.Users.Me;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Api.V1.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The gitInfo property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Api.V1.Users.GitInfo.GitInfoRequestBuilder GitInfo
        {
            get => new global::Soenneker.OpenHands.OpenApiClient.Api.V1.Users.GitInfo.GitInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gitOrganizations property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Api.V1.Users.GitOrganizations.GitOrganizationsRequestBuilder GitOrganizations
        {
            get => new global::Soenneker.OpenHands.OpenApiClient.Api.V1.Users.GitOrganizations.GitOrganizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The me property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Api.V1.Users.Me.MeRequestBuilder Me
        {
            get => new global::Soenneker.OpenHands.OpenApiClient.Api.V1.Users.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.V1.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.V1.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/users", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
