// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\shared-events\{conversationId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithConversationItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.OpenHands.OpenApiClient.api.sharedEvents.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Item.Item.WithEventItemRequestBuilder"/></returns>
        public global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Item.Item.WithEventItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("eventId", position);
                return new global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Item.Item.WithEventItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Item.WithConversationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConversationItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/shared-events/{conversationId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Item.WithConversationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConversationItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/shared-events/{conversationId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
