// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenHands.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Search
{
    /// <summary>
    /// Builds and executes requests for operations under \api\shared-events\search
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/shared-events/search?conversation_id={conversation_id}{&kind__eq*,limit*,page_id*,sort_order*,timestamp__gte*,timestamp__lt*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/shared-events/search?conversation_id={conversation_id}{&kind__eq*,limit*,page_id*,sort_order*,timestamp__gte*,timestamp__lt*}", rawUrl)
        {
        }
        /// <summary>
        /// Search / List events for a shared conversation.Because non-viewable events (e.g. ``ConversationStateUpdateEvent``) arefiltered out after fetching, a single backend page may yield fewer itemsthan *limit*.  This method transparently fetches additional backend pagesuntil the requested *limit* is reached or there are no more results.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.EventPage"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.OpenHands.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenHands.OpenApiClient.Models.EventPage?> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Search.SearchRequestBuilder.SearchRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenHands.OpenApiClient.Models.EventPage> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Search.SearchRequestBuilder.SearchRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.OpenHands.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.OpenHands.OpenApiClient.Models.EventPage>(requestInfo, global::Soenneker.OpenHands.OpenApiClient.Models.EventPage.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Search / List events for a shared conversation.Because non-viewable events (e.g. ``ConversationStateUpdateEvent``) arefiltered out after fetching, a single backend page may yield fewer itemsthan *limit*.  This method transparently fetches additional backend pagesuntil the requested *limit* is reached or there are no more results.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Search.SearchRequestBuilder.SearchRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Search.SearchRequestBuilder.SearchRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Search.SearchRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Search.SearchRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.OpenHands.OpenApiClient.Api.SharedEvents.Search.SearchRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Search / List events for a shared conversation.Because non-viewable events (e.g. ``ConversationStateUpdateEvent``) arefiltered out after fetching, a single backend page may yield fewer itemsthan *limit*.  This method transparently fetches additional backend pagesuntil the requested *limit* is reached or there are no more results.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SearchRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("conversation_id")]
            public string? ConversationId { get; set; }
#nullable restore
#else
            [QueryParameter("conversation_id")]
            public string ConversationId { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("kind__eq")]
            public string? KindEq { get; set; }
#nullable restore
#else
            [QueryParameter("kind__eq")]
            public string KindEq { get; set; }
#endif
            [QueryParameter("limit")]
            public int? Limit { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page_id")]
            public string? PageId { get; set; }
#nullable restore
#else
            [QueryParameter("page_id")]
            public string PageId { get; set; }
#endif
            [QueryParameter("sort_order")]
            public global::Soenneker.OpenHands.OpenApiClient.Models.EventSortOrder? SortOrder { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("timestamp__gte")]
            public string? TimestampGte { get; set; }
#nullable restore
#else
            [QueryParameter("timestamp__gte")]
            public string TimestampGte { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("timestamp__lt")]
            public string? TimestampLt { get; set; }
#nullable restore
#else
            [QueryParameter("timestamp__lt")]
            public string TimestampLt { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
