// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenHands.OpenApiClient.Api.Admin.VerifiedModels.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Api.Admin.VerifiedModels.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\admin\verified-models\{provider}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProviderItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.OpenHands.OpenApiClient.api.admin.verifiedModels.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.Admin.VerifiedModels.Item.Item.WithModel_nameItemRequestBuilder"/></returns>
        public global::Soenneker.OpenHands.OpenApiClient.Api.Admin.VerifiedModels.Item.Item.WithModel_nameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("model_name", position);
                return new global::Soenneker.OpenHands.OpenApiClient.Api.Admin.VerifiedModels.Item.Item.WithModel_nameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.Admin.VerifiedModels.Item.WithProviderItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProviderItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/admin/verified-models/{provider}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.Admin.VerifiedModels.Item.WithProviderItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProviderItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/admin/verified-models/{provider}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
