// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenHands.OpenApiClient.Api.V1.Git.Branches;
using Soenneker.OpenHands.OpenApiClient.Api.V1.Git.Installations;
using Soenneker.OpenHands.OpenApiClient.Api.V1.Git.Repositories;
using Soenneker.OpenHands.OpenApiClient.Api.V1.Git.SuggestedTasks;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Api.V1.Git
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\git
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GitRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The branches property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Api.V1.Git.Branches.BranchesRequestBuilder Branches
        {
            get => new global::Soenneker.OpenHands.OpenApiClient.Api.V1.Git.Branches.BranchesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The installations property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Api.V1.Git.Installations.InstallationsRequestBuilder Installations
        {
            get => new global::Soenneker.OpenHands.OpenApiClient.Api.V1.Git.Installations.InstallationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repositories property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Api.V1.Git.Repositories.RepositoriesRequestBuilder Repositories
        {
            get => new global::Soenneker.OpenHands.OpenApiClient.Api.V1.Git.Repositories.RepositoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The suggestedTasks property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Api.V1.Git.SuggestedTasks.SuggestedTasksRequestBuilder SuggestedTasks
        {
            get => new global::Soenneker.OpenHands.OpenApiClient.Api.V1.Git.SuggestedTasks.SuggestedTasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.V1.Git.GitRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GitRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/git", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.V1.Git.GitRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GitRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/git", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
