// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>Which ACP-compatible backend to launch. The provider&apos;s credential env-var name is derived from this via the ACP_PROVIDERS registry.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AcpAgentProfileAcpServer
    {
        [EnumMember(Value = "claude-code")]
        #pragma warning disable CS1591
        ClaudeCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "codex")]
        #pragma warning disable CS1591
        Codex,
        #pragma warning restore CS1591
        [EnumMember(Value = "gemini-cli")]
        #pragma warning disable CS1591
        GeminiCli,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
    }
}
