// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// &quot;Declarative mapping from a reserved \&quot;file-content\&quot; secret to a credentialfile the ACP subprocess authenticates from.Some providers read their credential from a *file on disk* rather than anenv var: Codex reads ``$CODEX_HOME/auth.json``; Gemini (Vertex AI) reads aservice-account JSON pointed at by ``GOOGLE_APPLICATION_CREDENTIALS``. Theuser supplies that credential as a pasted blob — a reserved secret named:attr:`secret_name` — and :class:`~openhands.sdk.agent.ACPAgent` materialisesit to :attr:`filename` under the conversation&apos;s durable per-conversation root(seed-if-absent), then sets :attr:`env_var` so the CLI can find it.Materialisation is keyed off :attr:`secret_name` (not the launch command),so a custom or aliased ``acp_command`` still works as long as the reservedsecret is supplied.The SDK owns the *mechanism* (writing the file in the runtime pod, settingthe env var, seed-if-absent, permissions); the *policy* — which secrets mapto which files for which CLIs — lives in these specs. Built-in defaultscover the supported providers, but downstream applications can override:attr:`~openhands.sdk.agent.ACPAgent.acp_file_secrets` to support other ACPservers with different file-auth schemes without an SDK change.&quot;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AcpFileSecretSpec : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The env_points_to property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Models.AcpFileSecretSpecEnvPointsTo? EnvPointsTo { get; set; }
        /// <summary>The env_var property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnvVar { get; set; }
#nullable restore
#else
        public string EnvVar { get; set; }
#endif
        /// <summary>The filename property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Filename { get; set; }
#nullable restore
#else
        public string Filename { get; set; }
#endif
        /// <summary>The secret_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecretName { get; set; }
#nullable restore
#else
        public string SecretName { get; set; }
#endif
        /// <summary>The subdir property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subdir { get; set; }
#nullable restore
#else
        public string Subdir { get; set; }
#endif
        /// <summary>The warn_if_unset property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? WarnIfUnset { get; set; }
#nullable restore
#else
        public List<string> WarnIfUnset { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.AcpFileSecretSpec"/> and sets the default values.
        /// </summary>
        public AcpFileSecretSpec()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.AcpFileSecretSpec"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.AcpFileSecretSpec CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.AcpFileSecretSpec();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "env_points_to", n => { EnvPointsTo = n.GetEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.AcpFileSecretSpecEnvPointsTo>(); } },
                { "env_var", n => { EnvVar = n.GetStringValue(); } },
                { "filename", n => { Filename = n.GetStringValue(); } },
                { "secret_name", n => { SecretName = n.GetStringValue(); } },
                { "subdir", n => { Subdir = n.GetStringValue(); } },
                { "warn_if_unset", n => { WarnIfUnset = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.AcpFileSecretSpecEnvPointsTo>("env_points_to", EnvPointsTo);
            writer.WriteStringValue("env_var", EnvVar);
            writer.WriteStringValue("filename", Filename);
            writer.WriteStringValue("secret_name", SecretName);
            writer.WriteStringValue("subdir", Subdir);
            writer.WriteCollectionOfPrimitiveValues<string>("warn_if_unset", WarnIfUnset);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
