// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>The commands to run. Allowed options are: `spawn`, `delegate`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ActionOutput_command
    {
        [EnumMember(Value = "spawn")]
        #pragma warning disable CS1591
        Spawn,
        #pragma warning restore CS1591
        [EnumMember(Value = "delegate")]
        #pragma warning disable CS1591
        Delegate,
        #pragma warning restore CS1591
    }
}
