// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.RedactedThinkingBlock"/>, <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ThinkingBlock"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActionEventInputThinkingBlocksItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.RedactedThinkingBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.RedactedThinkingBlock? RedactedThinkingBlock { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.RedactedThinkingBlock RedactedThinkingBlock { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ThinkingBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ThinkingBlock? ThinkingBlock { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ThinkingBlock ThinkingBlock { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionEventInputThinkingBlocksItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionEventInputThinkingBlocksItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionEventInputThinkingBlocksItem();
            result.RedactedThinkingBlock = new global::Soenneker.OpenHands.OpenApiClient.Models.RedactedThinkingBlock();
            result.ThinkingBlock = new global::Soenneker.OpenHands.OpenApiClient.Models.ThinkingBlock();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(RedactedThinkingBlock != null || ThinkingBlock != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(RedactedThinkingBlock, ThinkingBlock);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.RedactedThinkingBlock>(null, RedactedThinkingBlock, ThinkingBlock);
        }
    }
}
#pragma warning restore CS0618
