// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ActionInput : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional parameter of `spawn` command. List of agent types for each ID (e.g., [&apos;researcher&apos;, &apos;programmer&apos;]). If omitted or blank for an ID, the default general-purpose agent is used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_agent_types? AgentTypes { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_agent_types AgentTypes { get; set; }
#endif
        /// <summary>The commands to run. Allowed options are: `spawn`, `delegate`.</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_command? Command { get; set; }
        /// <summary>The content to write to the file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>Custom query to ask Tom agent (only used when use_user_message is False)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_custom_query? CustomQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_custom_query CustomQuery { get; set; }
#endif
        /// <summary>Dynamic data fields from the tool call</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_data? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_data Data { get; set; }
#endif
        /// <summary>A short (3-5 word) description of the task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_description? Description { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_description Description { get; set; }
#endif
        /// <summary>Direction to scroll. Options: &apos;up&apos;, &apos;down&apos;. Default: &apos;down&apos;</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_direction? Direction { get; set; }
        /// <summary>The path to the directory to list. Defaults to current directory.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DirPath { get; set; }
#nullable restore
#else
        public string DirPath { get; set; }
#endif
        /// <summary>Number of replacements expected. Defaults to 1. Use when you want to replace multiple occurrences. The edit will fail if the actual count doesn&apos;t match.</summary>
        public int? ExpectedReplacements { get; set; }
        /// <summary>Whether to include links in the content (default: False)</summary>
        public bool? ExtractLinks { get; set; }
        /// <summary>The path to the file to modify.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FilePath { get; set; }
#nullable restore
#else
        public string FilePath { get; set; }
#endif
        /// <summary>Required parameter of `create` command, with the content of the file to be created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_file_text? FileText { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_file_text FileText { get; set; }
#endif
        /// <summary>Required parameter of `spawn` command. List of identifiers to initialize sub-agents with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_ids? Ids { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_ids Ids { get; set; }
#endif
        /// <summary>Optional file pattern to filter which files to search (e.g., &quot;*.js&quot;, &quot;*.{ts,tsx}&quot;)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_include? Include { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_include Include { get; set; }
#endif
        /// <summary>Whether to include a screenshot of the current page. Default: False</summary>
        public bool? IncludeScreenshot { get; set; }
        /// <summary>The index of the element to click (from browser_get_state)</summary>
        public int? Index { get; set; }
        /// <summary>Required parameter of `insert` command. The `new_str` will be inserted AFTER the line `insert_line` of `path`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_insert_line? InsertLine { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_insert_line InsertLine { get; set; }
#endif
        /// <summary>If True, the command is an input to the running process. If False, the command is executed in the terminal session. Default is False.</summary>
        public bool? IsInput { get; set; }
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kind { get; set; }
#nullable restore
#else
        public string Kind { get; set; }
#endif
        /// <summary>Optional: Maximum number of lines to read. Use with &apos;offset&apos; to paginate through large files.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_limit? Limit { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_limit Limit { get; set; }
#endif
        /// <summary>Final message to send to the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>Name of the loaded skill to invoke.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Optional parameter of `str_replace` command containing the new string (if not given, no string will be added). Required parameter of `insert` command containing the string to insert.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_new_str? NewStr { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_new_str NewStr { get; set; }
#endif
        /// <summary>The text to replace it with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NewString { get; set; }
#nullable restore
#else
        public string NewString { get; set; }
#endif
        /// <summary>Whether to open any resulting navigation in a new tab. Default: False</summary>
        public bool? NewTab { get; set; }
        /// <summary>Optional: The 0-based line number to start reading from. Use for paginating through large files.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_offset? Offset { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_offset Offset { get; set; }
#endif
        /// <summary>Required parameter of `str_replace` command containing the string in `path` to replace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_old_str? OldStr { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_old_str OldStr { get; set; }
#endif
        /// <summary>The text to replace. To create a new file, use an empty string. Must match the exact text in the file including whitespace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OldString { get; set; }
#nullable restore
#else
        public string OldString { get; set; }
#endif
        /// <summary>Patch content following the &apos;*** Begin Patch&apos; ... &apos;*** End Patch&apos; format as described in OpenAI GPT-5.1 prompting guide.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Patch { get; set; }
#nullable restore
#else
        public string Patch { get; set; }
#endif
        /// <summary>Absolute path to file or directory.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The glob pattern to match files (e.g., &quot;**/*.js&quot;, &quot;src/**/*.ts&quot;)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pattern { get; set; }
#nullable restore
#else
        public string Pattern { get; set; }
#endif
        /// <summary>The task for the agent to perform.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>Brief explanation of why you need Tom agent consultation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>Whether to list subdirectories recursively (up to 2 levels).</summary>
        public bool? Recursive { get; set; }
        /// <summary>If True, reset the terminal by creating a new session. Use this only when the terminal becomes unresponsive. Note that all previously set environment variables and session state will be lost after reset. Cannot be used with is_input=True.</summary>
        public bool? Reset { get; set; }
        /// <summary>Task ID of the task to resume from.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_resume? Resume { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_resume Resume { get; set; }
#endif
        /// <summary>Character index to start from in the page content (default: 0)</summary>
        public int? StartFromChar { get; set; }
        /// <summary>Storage state dictionary containing &apos;cookies&apos; and &apos;origins&apos; (from browser_get_storage)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_storage_state? StorageState { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_storage_state StorageState { get; set; }
#endif
        /// <summary>The type of specialized agent to use for this task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubagentType { get; set; }
#nullable restore
#else
        public string SubagentType { get; set; }
#endif
        /// <summary>4 Character Tab ID of the tab to close (from browser_list_tabs)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TabId { get; set; }
#nullable restore
#else
        public string TabId { get; set; }
#endif
        /// <summary>The full task list. Required parameter of `plan` command.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.TaskItem>? TaskList { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.TaskItem> TaskList { get; set; }
#endif
        /// <summary>Required parameter of `delegate` command. Dictionary mapping sub-agent identifiers to task descriptions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Tasks { get; set; }
#nullable restore
#else
        public UntypedNode Tasks { get; set; }
#endif
        /// <summary>The text to type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The thought to log.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Thought { get; set; }
#nullable restore
#else
        public string Thought { get; set; }
#endif
        /// <summary>Optional. Sets a maximum time limit (in seconds) for running the command. If the command takes longer than this limit, you’ll be asked whether to continue or stop it. If you don’t set a value, the command will instead pause and ask for confirmation when it produces no new output for 30 seconds. Use a higher value if the command is expected to take a long time (like installation or testing), or if it has a known fixed duration (like sleep).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_timeout? Timeout { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_timeout Timeout { get; set; }
#endif
        /// <summary>The URL to navigate to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>Whether to consult about the user message (True) or provide custom query (False)</summary>
        public bool? UseUserMessage { get; set; }
        /// <summary>Optional parameter of `view` command when `path` points to a file. If none is given, the full file is shown. If provided, the file will be shown in the indicated line number range, e.g. [11, 12] will show lines 11 and 12. Indexing at 1 to start. Setting `[start_line, -1]` shows all lines from `start_line` to the end of the file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_view_range? ViewRange { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_view_range ViewRange { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput"/> and sets the default values.
        /// </summary>
        public ActionInput()
        {
            AdditionalData = new Dictionary<string, object>();
            Direction = global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_direction.Down;
            DirPath = ".";
            SubagentType = "general-purpose";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent_types", n => { AgentTypes = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_agent_types>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_agent_types.CreateFromDiscriminatorValue); } },
                { "command", n => { Command = n.GetEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_command>(); } },
                { "content", n => { Content = n.GetStringValue(); } },
                { "custom_query", n => { CustomQuery = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_custom_query>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_custom_query.CreateFromDiscriminatorValue); } },
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_data>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_data.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_description>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_description.CreateFromDiscriminatorValue); } },
                { "dir_path", n => { DirPath = n.GetStringValue(); } },
                { "direction", n => { Direction = n.GetEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_direction>(); } },
                { "expected_replacements", n => { ExpectedReplacements = n.GetIntValue(); } },
                { "extract_links", n => { ExtractLinks = n.GetBoolValue(); } },
                { "file_path", n => { FilePath = n.GetStringValue(); } },
                { "file_text", n => { FileText = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_file_text>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_file_text.CreateFromDiscriminatorValue); } },
                { "ids", n => { Ids = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_ids>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_ids.CreateFromDiscriminatorValue); } },
                { "include", n => { Include = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_include>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_include.CreateFromDiscriminatorValue); } },
                { "include_screenshot", n => { IncludeScreenshot = n.GetBoolValue(); } },
                { "index", n => { Index = n.GetIntValue(); } },
                { "insert_line", n => { InsertLine = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_insert_line>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_insert_line.CreateFromDiscriminatorValue); } },
                { "is_input", n => { IsInput = n.GetBoolValue(); } },
                { "kind", n => { Kind = n.GetStringValue(); } },
                { "limit", n => { Limit = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_limit>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_limit.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "new_str", n => { NewStr = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_new_str>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_new_str.CreateFromDiscriminatorValue); } },
                { "new_string", n => { NewString = n.GetStringValue(); } },
                { "new_tab", n => { NewTab = n.GetBoolValue(); } },
                { "offset", n => { Offset = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_offset>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_offset.CreateFromDiscriminatorValue); } },
                { "old_str", n => { OldStr = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_old_str>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_old_str.CreateFromDiscriminatorValue); } },
                { "old_string", n => { OldString = n.GetStringValue(); } },
                { "patch", n => { Patch = n.GetStringValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "pattern", n => { Pattern = n.GetStringValue(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "recursive", n => { Recursive = n.GetBoolValue(); } },
                { "reset", n => { Reset = n.GetBoolValue(); } },
                { "resume", n => { Resume = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_resume>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_resume.CreateFromDiscriminatorValue); } },
                { "start_from_char", n => { StartFromChar = n.GetIntValue(); } },
                { "storage_state", n => { StorageState = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_storage_state>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_storage_state.CreateFromDiscriminatorValue); } },
                { "subagent_type", n => { SubagentType = n.GetStringValue(); } },
                { "tab_id", n => { TabId = n.GetStringValue(); } },
                { "task_list", n => { TaskList = n.GetCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.TaskItem>(global::Soenneker.OpenHands.OpenApiClient.Models.TaskItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tasks", n => { Tasks = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "thought", n => { Thought = n.GetStringValue(); } },
                { "timeout", n => { Timeout = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_timeout>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_timeout.CreateFromDiscriminatorValue); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "use_user_message", n => { UseUserMessage = n.GetBoolValue(); } },
                { "view_range", n => { ViewRange = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_view_range>(global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_view_range.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_agent_types>("agent_types", AgentTypes);
            writer.WriteEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_command>("command", Command);
            writer.WriteStringValue("content", Content);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_custom_query>("custom_query", CustomQuery);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_data>("data", Data);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_description>("description", Description);
            writer.WriteEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_direction>("direction", Direction);
            writer.WriteStringValue("dir_path", DirPath);
            writer.WriteIntValue("expected_replacements", ExpectedReplacements);
            writer.WriteBoolValue("extract_links", ExtractLinks);
            writer.WriteStringValue("file_path", FilePath);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_file_text>("file_text", FileText);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_ids>("ids", Ids);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_include>("include", Include);
            writer.WriteBoolValue("include_screenshot", IncludeScreenshot);
            writer.WriteIntValue("index", Index);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_insert_line>("insert_line", InsertLine);
            writer.WriteBoolValue("is_input", IsInput);
            writer.WriteStringValue("kind", Kind);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_limit>("limit", Limit);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_new_str>("new_str", NewStr);
            writer.WriteStringValue("new_string", NewString);
            writer.WriteBoolValue("new_tab", NewTab);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_offset>("offset", Offset);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_old_str>("old_str", OldStr);
            writer.WriteStringValue("old_string", OldString);
            writer.WriteStringValue("patch", Patch);
            writer.WriteStringValue("path", Path);
            writer.WriteStringValue("pattern", Pattern);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteStringValue("reason", Reason);
            writer.WriteBoolValue("recursive", Recursive);
            writer.WriteBoolValue("reset", Reset);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_resume>("resume", Resume);
            writer.WriteIntValue("start_from_char", StartFromChar);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_storage_state>("storage_state", StorageState);
            writer.WriteStringValue("subagent_type", SubagentType);
            writer.WriteStringValue("tab_id", TabId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.TaskItem>("task_list", TaskList);
            writer.WriteObjectValue<UntypedNode>("tasks", Tasks);
            writer.WriteStringValue("text", Text);
            writer.WriteStringValue("thought", Thought);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_timeout>("timeout", Timeout);
            writer.WriteStringValue("url", Url);
            writer.WriteBoolValue("use_user_message", UseUserMessage);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_view_range>("view_range", ViewRange);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_agent_typesMember1"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_agent_types : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_agent_typesMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_agent_typesMember1? ActionInputAgentTypesMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_agent_typesMember1 ActionInputAgentTypesMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_agent_types"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_agent_types CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_agent_types();
                if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ActionInputAgentTypesMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_agent_typesMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputAgentTypesMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputAgentTypesMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_agent_typesMember1>(null, ActionInputAgentTypesMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_custom_queryMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_custom_query : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_custom_queryMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_custom_queryMember1? ActionInputCustomQueryMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_custom_queryMember1 ActionInputCustomQueryMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_custom_query"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_custom_query CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_custom_query();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ActionInputCustomQueryMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_custom_queryMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputCustomQueryMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputCustomQueryMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_custom_queryMember1>(null, ActionInputCustomQueryMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_descriptionMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_description : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_descriptionMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_descriptionMember1? ActionInputDescriptionMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_descriptionMember1 ActionInputDescriptionMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_description"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_description CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_description();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ActionInputDescriptionMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_descriptionMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputDescriptionMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputDescriptionMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_descriptionMember1>(null, ActionInputDescriptionMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_file_textMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_file_text : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_file_textMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_file_textMember1? ActionInputFileTextMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_file_textMember1 ActionInputFileTextMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_file_text"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_file_text CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_file_text();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ActionInputFileTextMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_file_textMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputFileTextMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputFileTextMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_file_textMember1>(null, ActionInputFileTextMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_idsMember1"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_ids : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_idsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_idsMember1? ActionInputIdsMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_idsMember1 ActionInputIdsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_ids"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_ids CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_ids();
                if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ActionInputIdsMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_idsMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputIdsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputIdsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_idsMember1>(null, ActionInputIdsMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_includeMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_include : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_includeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_includeMember1? ActionInputIncludeMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_includeMember1 ActionInputIncludeMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_include"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_include CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_include();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ActionInputIncludeMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_includeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputIncludeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputIncludeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_includeMember1>(null, ActionInputIncludeMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_insert_lineMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_insert_line : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_insert_lineMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_insert_lineMember1? ActionInputInsertLineMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_insert_lineMember1 ActionInputInsertLineMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_insert_line"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_insert_line CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_insert_line();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.ActionInputInsertLineMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_insert_lineMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputInsertLineMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputInsertLineMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_insert_lineMember1>(null, ActionInputInsertLineMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_limitMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_limit : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_limitMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_limitMember1? ActionInputLimitMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_limitMember1 ActionInputLimitMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_limit"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_limit CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_limit();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.ActionInputLimitMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_limitMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputLimitMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputLimitMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_limitMember1>(null, ActionInputLimitMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_new_strMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_new_str : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_new_strMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_new_strMember1? ActionInputNewStrMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_new_strMember1 ActionInputNewStrMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_new_str"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_new_str CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_new_str();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ActionInputNewStrMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_new_strMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputNewStrMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputNewStrMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_new_strMember1>(null, ActionInputNewStrMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_offsetMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_offset : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_offsetMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_offsetMember1? ActionInputOffsetMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_offsetMember1 ActionInputOffsetMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_offset"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_offset CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_offset();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.ActionInputOffsetMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_offsetMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputOffsetMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputOffsetMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_offsetMember1>(null, ActionInputOffsetMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_old_strMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_old_str : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_old_strMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_old_strMember1? ActionInputOldStrMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_old_strMember1 ActionInputOldStrMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_old_str"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_old_str CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_old_str();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ActionInputOldStrMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_old_strMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputOldStrMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputOldStrMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_old_strMember1>(null, ActionInputOldStrMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_resumeMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_resume : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_resumeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_resumeMember1? ActionInputResumeMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_resumeMember1 ActionInputResumeMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_resume"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_resume CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_resume();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ActionInputResumeMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_resumeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputResumeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputResumeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_resumeMember1>(null, ActionInputResumeMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_timeoutMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_timeout : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_timeoutMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_timeoutMember1? ActionInputTimeoutMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_timeoutMember1 ActionInputTimeoutMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_timeout"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_timeout CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_timeout();
                if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else {
                    result.ActionInputTimeoutMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_timeoutMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputTimeoutMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputTimeoutMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_timeoutMember1>(null, ActionInputTimeoutMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_view_rangeMember1"/>, List&lt;int&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionInput_view_range : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_view_rangeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_view_rangeMember1? ActionInputViewRangeMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_view_rangeMember1 ActionInputViewRangeMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;int&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<int?>? Integer { get; set; }
#nullable restore
#else
            public List<int?> Integer { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_view_range"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_view_range CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput.ActionInput_view_range();
                if(parseNode.GetCollectionOfPrimitiveValues<int?>()?.AsList() is List<int?> integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.ActionInputViewRangeMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_view_rangeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionInputViewRangeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionInputViewRangeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<int?>(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ActionInput_view_rangeMember1>(null, ActionInputViewRangeMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
