// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.AcpAgentProfile"/>, <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfile"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AgentProfileDetailResponseProfile : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.AcpAgentProfile"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.AcpAgentProfile? AcpAgentProfile { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.AcpAgentProfile AcpAgentProfile { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfile"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfile? OpenHandsAgentProfile { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfile OpenHandsAgentProfile { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.AgentProfileDetailResponseProfile"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.AgentProfileDetailResponseProfile CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.OpenHands.OpenApiClient.Models.AgentProfileDetailResponseProfile();
            if("AcpAgentProfile".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AcpAgentProfile = new global::Soenneker.OpenHands.OpenApiClient.Models.AcpAgentProfile();
            }
            else if("OpenHandsAgentProfile".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.OpenHandsAgentProfile = new global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfile();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AcpAgentProfile != null)
            {
                return AcpAgentProfile.GetFieldDeserializers();
            }
            else if(OpenHandsAgentProfile != null)
            {
                return OpenHandsAgentProfile.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(AcpAgentProfile != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.AcpAgentProfile>(null, AcpAgentProfile);
            }
            else if(OpenHandsAgentProfile != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfile>(null, OpenHandsAgentProfile);
            }
        }
    }
}
#pragma warning restore CS0618
