// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiKeyResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The expires_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_expires_at? ExpiresAt { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_expires_at ExpiresAt { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The last_used_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_last_used_at? LastUsedAt { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_last_used_at LastUsedAt { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_name? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_name Name { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse"/> and sets the default values.
        /// </summary>
        public ApiKeyResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_expires_at>(global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_expires_at.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "last_used_at", n => { LastUsedAt = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_last_used_at>(global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_last_used_at.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_name>(global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_name.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_expires_at>("expires_at", ExpiresAt);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_last_used_at>("last_used_at", LastUsedAt);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_name>("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_expires_atMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApiKeyResponse_expires_at : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_expires_atMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_expires_atMember1? ApiKeyResponseExpiresAtMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_expires_atMember1 ApiKeyResponseExpiresAtMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_expires_at"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_expires_at CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_expires_at();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.ApiKeyResponseExpiresAtMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_expires_atMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ApiKeyResponseExpiresAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ApiKeyResponseExpiresAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_expires_atMember1>(null, ApiKeyResponseExpiresAtMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_last_used_atMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApiKeyResponse_last_used_at : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_last_used_atMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_last_used_atMember1? ApiKeyResponseLastUsedAtMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_last_used_atMember1 ApiKeyResponseLastUsedAtMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_last_used_at"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_last_used_at CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_last_used_at();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.ApiKeyResponseLastUsedAtMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_last_used_atMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ApiKeyResponseLastUsedAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ApiKeyResponseLastUsedAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_last_used_atMember1>(null, ApiKeyResponseLastUsedAtMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_nameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApiKeyResponse_name : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_nameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_nameMember1? ApiKeyResponseNameMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_nameMember1 ApiKeyResponseNameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_name"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_name CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse.ApiKeyResponse_name();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ApiKeyResponseNameMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_nameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ApiKeyResponseNameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ApiKeyResponseNameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ApiKeyResponse_nameMember1>(null, ApiKeyResponseNameMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
