// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AppMode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "oss")]
        #pragma warning disable CS1591
        Oss,
        #pragma warning restore CS1591
        [EnumMember(Value = "saas")]
        #pragma warning disable CS1591
        Saas,
        #pragma warning restore CS1591
    }
}
