// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.LocalWorkspaceInput"/>, <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.RemoteWorkspace"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BaseWorkspace : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.LocalWorkspaceInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.LocalWorkspaceInput? LocalWorkspaceInput { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.LocalWorkspaceInput LocalWorkspaceInput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.RemoteWorkspace"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.RemoteWorkspace? RemoteWorkspace { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.RemoteWorkspace RemoteWorkspace { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.BaseWorkspace"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.BaseWorkspace CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("kind")?.GetStringValue();
            var result = new global::Soenneker.OpenHands.OpenApiClient.Models.BaseWorkspace();
            if("openhands__sdk__workspace__local__LocalWorkspace-Input__1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.LocalWorkspaceInput = new global::Soenneker.OpenHands.OpenApiClient.Models.LocalWorkspaceInput();
            }
            else if("openhands__sdk__workspace__remote__base__RemoteWorkspace-Input__1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.RemoteWorkspace = new global::Soenneker.OpenHands.OpenApiClient.Models.RemoteWorkspace();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(LocalWorkspaceInput != null)
            {
                return LocalWorkspaceInput.GetFieldDeserializers();
            }
            else if(RemoteWorkspace != null)
            {
                return RemoteWorkspace.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(LocalWorkspaceInput != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.LocalWorkspaceInput>(null, LocalWorkspaceInput);
            }
            else if(RemoteWorkspace != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.RemoteWorkspace>(null, RemoteWorkspace);
            }
        }
    }
}
#pragma warning restore CS0618
