// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// A tool defined by the client, executed externally (not by the SDK).Clients pass these specs in ``POST /conversations`` to register toolswhose execution is handled outside the SDK (e.g., by a frontendlistening for ActionEvents over WebSocket).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClientToolSpec : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional MCP-style annotations for the tool. When omitted, the tool is treated conservatively (not read-only), so the agent is asked to predict a security risk before calling it.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpecAnnotations? Annotations { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpecAnnotations Annotations { get; set; }
#endif
        /// <summary>Description shown to the LLM explaining when and how to use this tool.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Unique tool name the agent will use to call this tool.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>JSON Schema describing the tool&apos;s input parameters. Must be an object schema.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpecParametersProperty? Parameters { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpecParametersProperty Parameters { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpec"/> and sets the default values.
        /// </summary>
        public ClientToolSpec()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpec"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpec CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpec();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "annotations", n => { Annotations = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpecAnnotations>(global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpecAnnotations.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parameters", n => { Parameters = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpecParametersProperty>(global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpecParametersProperty.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpecAnnotations>("annotations", Annotations);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolSpecParametersProperty>("parameters", Parameters);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
