// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// A tool whose execution is deferred to the external client.Created from a :class:`ClientToolSpec` at conversation start. The agentsees it as a normal tool and can call it; the ActionEvent is emittedover WebSocket for the client to handle.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClientToolOutput : IAdditionalDataHolder, IParsable
    {
        /// <summary>The action_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionType { get; set; }
#nullable restore
#else
        public string ActionType { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The annotations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputAnnotations? Annotations { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputAnnotations Annotations { get; set; }
#endif
        /// <summary>Per-instance tool name from the ClientToolSpec.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientToolName { get; set; }
#nullable restore
#else
        public string ClientToolName { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The original JSON Schema for the tool&apos;s parameters, as provided by the client. Used verbatim when exporting the tool to the LLM so client-defined constraints (enum, nested objects, bounds, additionalProperties, ...) are preserved.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputInputSchemaProperty? InputSchema { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputInputSchemaProperty InputSchema { get; set; }
#endif
        /// <summary>The kind property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutput_kind? Kind { get; set; }
        /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputMeta? Meta { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputMeta Meta { get; set; }
#endif
        /// <summary>The observation_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObservationType { get; set; }
#nullable restore
#else
        public string ObservationType { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; private set; }
#nullable restore
#else
        public string Title { get; private set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutput"/> and sets the default values.
        /// </summary>
        public ClientToolOutput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action_type", n => { ActionType = n.GetStringValue(); } },
                { "annotations", n => { Annotations = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputAnnotations>(global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputAnnotations.CreateFromDiscriminatorValue); } },
                { "client_tool_name", n => { ClientToolName = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "input_schema", n => { InputSchema = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputInputSchemaProperty>(global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputInputSchemaProperty.CreateFromDiscriminatorValue); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutput_kind>(); } },
                { "meta", n => { Meta = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputMeta>(global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputMeta.CreateFromDiscriminatorValue); } },
                { "observation_type", n => { ObservationType = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action_type", ActionType);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputAnnotations>("annotations", Annotations);
            writer.WriteStringValue("client_tool_name", ClientToolName);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputInputSchemaProperty>("input_schema", InputSchema);
            writer.WriteEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutput_kind>("kind", Kind);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ClientToolOutputMeta>("meta", Meta);
            writer.WriteStringValue("observation_type", ObservationType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
