// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConversationSettings : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Require user confirmation before executing risky actions.</summary>
        public bool? ConfirmationMode { get; set; }
        /// <summary>Maximum number of iterations the conversation will run before stopping.</summary>
        public int? MaxIterations { get; set; }
        /// <summary>The schema_version property</summary>
        public int? SchemaVersion { get; set; }
        /// <summary>Security analyzer that evaluates actions before execution.</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Models.ConversationSettingsSecurityAnalyzer? SecurityAnalyzer { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ConversationSettings"/> and sets the default values.
        /// </summary>
        public ConversationSettings()
        {
            AdditionalData = new Dictionary<string, object>();
            ConfirmationMode = false;
            MaxIterations = 500;
            SchemaVersion = 1;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ConversationSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.ConversationSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.ConversationSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "confirmation_mode", n => { ConfirmationMode = n.GetBoolValue(); } },
                { "max_iterations", n => { MaxIterations = n.GetIntValue(); } },
                { "schema_version", n => { SchemaVersion = n.GetIntValue(); } },
                { "security_analyzer", n => { SecurityAnalyzer = n.GetEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.ConversationSettingsSecurityAnalyzer>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("confirmation_mode", ConfirmationMode);
            writer.WriteIntValue("max_iterations", MaxIterations);
            writer.WriteIntValue("schema_version", SchemaVersion);
            writer.WriteEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.ConversationSettingsSecurityAnalyzer>("security_analyzer", SecurityAnalyzer);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
