// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// &quot;Encapsulates fallback behavior for LLM calls.When the primary LLM fails with a transient error (after retries),this strategy tries alternate LLMs loaded from LLMProfileStore profiles.Fallback is per-call: each new request starts with the primary model.&quot;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FallbackStrategy : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Ordered list of LLM profile names to try on transient failure.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FallbackLlms { get; set; }
#nullable restore
#else
        public List<string> FallbackLlms { get; set; }
#endif
        /// <summary>Path to directory containing profiles. If not specified, defaults to `.openhands/profiles`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.Profile_Store_Dir? ProfileStoreDir { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.Profile_Store_Dir ProfileStoreDir { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.FallbackStrategy"/> and sets the default values.
        /// </summary>
        public FallbackStrategy()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.FallbackStrategy"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.FallbackStrategy CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.FallbackStrategy();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "fallback_llms", n => { FallbackLlms = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "profile_store_dir", n => { ProfileStoreDir = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.Profile_Store_Dir>(global::Soenneker.OpenHands.OpenApiClient.Models.Profile_Store_Dir.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("fallback_llms", FallbackLlms);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.Profile_Store_Dir>("profile_store_dir", ProfileStoreDir);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
