// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// Settings with additional token data for the frontend
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetSettingsModel : IAdditionalDataHolder, IParsable
    {
        /// <summary>The active_agent_profile_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActiveAgentProfileId { get; set; }
#nullable restore
#else
        public string ActiveAgentProfileId { get; set; }
#endif
        /// <summary>The active_agent_profile_revision property</summary>
        public int? ActiveAgentProfileRevision { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agent_settings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelAgentSettingsProperty? AgentSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelAgentSettingsProperty AgentSettings { get; set; }
#endif
        /// <summary>The conversation_settings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ConversationSettings? ConversationSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ConversationSettings ConversationSettings { get; set; }
#endif
        /// <summary>The default_sandbox_spec_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultSandboxSpecId { get; set; }
#nullable restore
#else
        public string DefaultSandboxSpecId { get; set; }
#endif
        /// <summary>The disabled_skills property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelDisabledSkills? DisabledSkills { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelDisabledSkills DisabledSkills { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The email_verified property</summary>
        public bool? EmailVerified { get; set; }
        /// <summary>The enable_proactive_conversation_starters property</summary>
        public bool? EnableProactiveConversationStarters { get; set; }
        /// <summary>The enable_sound_notifications property</summary>
        public bool? EnableSoundNotifications { get; set; }
        /// <summary>The git_full_clone property</summary>
        public bool? GitFullClone { get; set; }
        /// <summary>The git_user_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GitUserEmail { get; set; }
#nullable restore
#else
        public string GitUserEmail { get; set; }
#endif
        /// <summary>The git_user_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GitUserName { get; set; }
#nullable restore
#else
        public string GitUserName { get; set; }
#endif
        /// <summary>&quot;Marketplaces inherited from instance or organization level. These are read-only and cannot be modified by the user. Computed at runtime: Instance defaults + Org defaults.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.OpenhandsAppServerSettingsSettingsModelsMarketplaceRegistration>? InheritedMarketplaces { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.OpenhandsAppServerSettingsSettingsModelsMarketplaceRegistration> InheritedMarketplaces { get; set; }
#endif
        /// <summary>The language property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>The llm_api_key_set property</summary>
        public bool? LlmApiKeySet { get; set; }
        /// <summary>Container for saved LLM configurations.Stores a named collection of ``LLM`` configurations plus the name of thecurrently active one (if any). All profile-management logic lives here;``Settings`` holds a single ``LLMProfiles`` instance and delegates to it.Invariants (enforced on validate + assignment):- ``active`` is either ``None`` or a key of ``profiles``.- Individual profiles that fail to parse (schema drift) are dropped with  a warning rather than failing the whole ``Settings`` load.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.LlmProfiles? LlmProfiles { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.LlmProfiles LlmProfiles { get; set; }
#endif
        /// <summary>The max_budget_per_task property</summary>
        public double? MaxBudgetPerTask { get; set; }
        /// <summary>The provider_tokens_set property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelProviderTokensSet? ProviderTokensSet { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelProviderTokensSet ProviderTokensSet { get; set; }
#endif
        /// <summary>List of marketplace registrations for plugin resolution. Marketplaces with auto_load=True will have their plugins loaded automatically at conversation start. See MarketplaceRegistration for details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.OpenhandsAppServerSettingsSettingsModelsMarketplaceRegistration>? RegisteredMarketplaces { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.OpenhandsAppServerSettingsSettingsModelsMarketplaceRegistration> RegisteredMarketplaces { get; set; }
#endif
        /// <summary>The remote_runtime_resource_factor property</summary>
        public int? RemoteRuntimeResourceFactor { get; set; }
        /// <summary>The sandbox_api_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SandboxApiKey { get; set; }
#nullable restore
#else
        public string SandboxApiKey { get; set; }
#endif
        /// <summary>The sandbox_base_container_image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SandboxBaseContainerImage { get; set; }
#nullable restore
#else
        public string SandboxBaseContainerImage { get; set; }
#endif
        /// <summary>Strategy for grouping conversations within sandboxes.</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Models.SandboxGroupingStrategy? SandboxGroupingStrategy { get; set; }
        /// <summary>The sandbox_runtime_container_image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SandboxRuntimeContainerImage { get; set; }
#nullable restore
#else
        public string SandboxRuntimeContainerImage { get; set; }
#endif
        /// <summary>The search_api_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchApiKey { get; set; }
#nullable restore
#else
        public string SearchApiKey { get; set; }
#endif
        /// <summary>The search_api_key_set property</summary>
        public bool? SearchApiKeySet { get; set; }
        /// <summary>The secrets_store property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelSecretsStore? SecretsStore { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelSecretsStore SecretsStore { get; set; }
#endif
        /// <summary>The user_consents_to_analytics property</summary>
        public bool? UserConsentsToAnalytics { get; set; }
        /// <summary>The user_version property</summary>
        public int? UserVersion { get; set; }
        /// <summary>The v1_enabled property</summary>
        public bool? V1Enabled { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModel"/> and sets the default values.
        /// </summary>
        public GetSettingsModel()
        {
            AdditionalData = new Dictionary<string, object>();
            EnableProactiveConversationStarters = true;
            EnableSoundNotifications = false;
            GitFullClone = false;
            SearchApiKeySet = false;
            V1Enabled = true;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active_agent_profile_id", n => { ActiveAgentProfileId = n.GetStringValue(); } },
                { "active_agent_profile_revision", n => { ActiveAgentProfileRevision = n.GetIntValue(); } },
                { "agent_settings", n => { AgentSettings = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelAgentSettingsProperty>(global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelAgentSettingsProperty.CreateFromDiscriminatorValue); } },
                { "conversation_settings", n => { ConversationSettings = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ConversationSettings>(global::Soenneker.OpenHands.OpenApiClient.Models.ConversationSettings.CreateFromDiscriminatorValue); } },
                { "default_sandbox_spec_id", n => { DefaultSandboxSpecId = n.GetStringValue(); } },
                { "disabled_skills", n => { DisabledSkills = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelDisabledSkills>(global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelDisabledSkills.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "email_verified", n => { EmailVerified = n.GetBoolValue(); } },
                { "enable_proactive_conversation_starters", n => { EnableProactiveConversationStarters = n.GetBoolValue(); } },
                { "enable_sound_notifications", n => { EnableSoundNotifications = n.GetBoolValue(); } },
                { "git_full_clone", n => { GitFullClone = n.GetBoolValue(); } },
                { "git_user_email", n => { GitUserEmail = n.GetStringValue(); } },
                { "git_user_name", n => { GitUserName = n.GetStringValue(); } },
                { "inherited_marketplaces", n => { InheritedMarketplaces = n.GetCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.OpenhandsAppServerSettingsSettingsModelsMarketplaceRegistration>(global::Soenneker.OpenHands.OpenApiClient.Models.OpenhandsAppServerSettingsSettingsModelsMarketplaceRegistration.CreateFromDiscriminatorValue)?.AsList(); } },
                { "language", n => { Language = n.GetStringValue(); } },
                { "llm_api_key_set", n => { LlmApiKeySet = n.GetBoolValue(); } },
                { "llm_profiles", n => { LlmProfiles = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.LlmProfiles>(global::Soenneker.OpenHands.OpenApiClient.Models.LlmProfiles.CreateFromDiscriminatorValue); } },
                { "max_budget_per_task", n => { MaxBudgetPerTask = n.GetDoubleValue(); } },
                { "provider_tokens_set", n => { ProviderTokensSet = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelProviderTokensSet>(global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelProviderTokensSet.CreateFromDiscriminatorValue); } },
                { "registered_marketplaces", n => { RegisteredMarketplaces = n.GetCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.OpenhandsAppServerSettingsSettingsModelsMarketplaceRegistration>(global::Soenneker.OpenHands.OpenApiClient.Models.OpenhandsAppServerSettingsSettingsModelsMarketplaceRegistration.CreateFromDiscriminatorValue)?.AsList(); } },
                { "remote_runtime_resource_factor", n => { RemoteRuntimeResourceFactor = n.GetIntValue(); } },
                { "sandbox_api_key", n => { SandboxApiKey = n.GetStringValue(); } },
                { "sandbox_base_container_image", n => { SandboxBaseContainerImage = n.GetStringValue(); } },
                { "sandbox_grouping_strategy", n => { SandboxGroupingStrategy = n.GetEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.SandboxGroupingStrategy>(); } },
                { "sandbox_runtime_container_image", n => { SandboxRuntimeContainerImage = n.GetStringValue(); } },
                { "search_api_key", n => { SearchApiKey = n.GetStringValue(); } },
                { "search_api_key_set", n => { SearchApiKeySet = n.GetBoolValue(); } },
                { "secrets_store", n => { SecretsStore = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelSecretsStore>(global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelSecretsStore.CreateFromDiscriminatorValue); } },
                { "user_consents_to_analytics", n => { UserConsentsToAnalytics = n.GetBoolValue(); } },
                { "user_version", n => { UserVersion = n.GetIntValue(); } },
                { "v1_enabled", n => { V1Enabled = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("active_agent_profile_id", ActiveAgentProfileId);
            writer.WriteIntValue("active_agent_profile_revision", ActiveAgentProfileRevision);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelAgentSettingsProperty>("agent_settings", AgentSettings);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ConversationSettings>("conversation_settings", ConversationSettings);
            writer.WriteStringValue("default_sandbox_spec_id", DefaultSandboxSpecId);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelDisabledSkills>("disabled_skills", DisabledSkills);
            writer.WriteStringValue("email", Email);
            writer.WriteBoolValue("email_verified", EmailVerified);
            writer.WriteBoolValue("enable_proactive_conversation_starters", EnableProactiveConversationStarters);
            writer.WriteBoolValue("enable_sound_notifications", EnableSoundNotifications);
            writer.WriteBoolValue("git_full_clone", GitFullClone);
            writer.WriteStringValue("git_user_email", GitUserEmail);
            writer.WriteStringValue("git_user_name", GitUserName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.OpenhandsAppServerSettingsSettingsModelsMarketplaceRegistration>("inherited_marketplaces", InheritedMarketplaces);
            writer.WriteStringValue("language", Language);
            writer.WriteBoolValue("llm_api_key_set", LlmApiKeySet);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.LlmProfiles>("llm_profiles", LlmProfiles);
            writer.WriteDoubleValue("max_budget_per_task", MaxBudgetPerTask);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelProviderTokensSet>("provider_tokens_set", ProviderTokensSet);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.OpenhandsAppServerSettingsSettingsModelsMarketplaceRegistration>("registered_marketplaces", RegisteredMarketplaces);
            writer.WriteIntValue("remote_runtime_resource_factor", RemoteRuntimeResourceFactor);
            writer.WriteStringValue("sandbox_api_key", SandboxApiKey);
            writer.WriteStringValue("sandbox_base_container_image", SandboxBaseContainerImage);
            writer.WriteEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.SandboxGroupingStrategy>("sandbox_grouping_strategy", SandboxGroupingStrategy);
            writer.WriteStringValue("sandbox_runtime_container_image", SandboxRuntimeContainerImage);
            writer.WriteStringValue("search_api_key", SearchApiKey);
            writer.WriteBoolValue("search_api_key_set", SearchApiKeySet);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.GetSettingsModelSecretsStore>("secrets_store", SecretsStore);
            writer.WriteBoolValue("user_consents_to_analytics", UserConsentsToAnalytics);
            writer.WriteIntValue("user_version", UserVersion);
            writer.WriteBoolValue("v1_enabled", V1Enabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
