// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GlobToolOutput_kind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "GlobTool")]
        #pragma warning disable CS1591
        GlobTool,
        #pragma warning restore CS1591
    }
}
