// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>Source is always &apos;hook&apos; for hook execution events</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum HookExecutionEventOutputSource
    {
        [EnumMember(Value = "agent")]
        #pragma warning disable CS1591
        Agent,
        #pragma warning restore CS1591
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "environment")]
        #pragma warning disable CS1591
        Environment,
        #pragma warning restore CS1591
        [EnumMember(Value = "hook")]
        #pragma warning disable CS1591
        Hook,
        #pragma warning restore CS1591
    }
}
