// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>Types of hooks that can be executed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum HookType
    {
        [EnumMember(Value = "command")]
        #pragma warning disable CS1591
        Command,
        #pragma warning restore CS1591
        [EnumMember(Value = "prompt")]
        #pragma warning disable CS1591
        Prompt,
        #pragma warning restore CS1591
    }
}
