// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// Callback processor for Jira Data Center V1 integrations.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JiraDcV1CallbackProcessorInput : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The base_api_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseApiUrl { get; set; }
#nullable restore
#else
        public string BaseApiUrl { get; set; }
#endif
        /// <summary>The issue_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IssueKey { get; set; }
#nullable restore
#else
        public string IssueKey { get; set; }
#endif
        /// <summary>The kind property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Models.JiraDcV1CallbackProcessorInput_kind? Kind { get; set; }
        /// <summary>The should_request_summary property</summary>
        public bool? ShouldRequestSummary { get; set; }
        /// <summary>The workspace_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkspaceName { get; set; }
#nullable restore
#else
        public string WorkspaceName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.JiraDcV1CallbackProcessorInput"/> and sets the default values.
        /// </summary>
        public JiraDcV1CallbackProcessorInput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.JiraDcV1CallbackProcessorInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.JiraDcV1CallbackProcessorInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.JiraDcV1CallbackProcessorInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base_api_url", n => { BaseApiUrl = n.GetStringValue(); } },
                { "issue_key", n => { IssueKey = n.GetStringValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.JiraDcV1CallbackProcessorInput_kind>(); } },
                { "should_request_summary", n => { ShouldRequestSummary = n.GetBoolValue(); } },
                { "workspace_name", n => { WorkspaceName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("base_api_url", BaseApiUrl);
            writer.WriteStringValue("issue_key", IssueKey);
            writer.WriteEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.JiraDcV1CallbackProcessorInput_kind>("kind", Kind);
            writer.WriteBoolValue("should_request_summary", ShouldRequestSummary);
            writer.WriteStringValue("workspace_name", WorkspaceName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
