// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum JiraV1CallbackProcessorInput_kind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "JiraV1CallbackProcessor")]
        #pragma warning disable CS1591
        JiraV1CallbackProcessor,
        #pragma warning restore CS1591
    }
}
