// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum LlmCompletionLogEventOutput_kind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "LLMCompletionLogEvent")]
        #pragma warning disable CS1591
        LlmCompletionLogEvent,
        #pragma warning restore CS1591
    }
}
