// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>Scope of a marketplace registration.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MarketplaceScope
    {
        [EnumMember(Value = "instance")]
        #pragma warning disable CS1591
        Instance,
        #pragma warning restore CS1591
        [EnumMember(Value = "org")]
        #pragma warning disable CS1591
        Org,
        #pragma warning restore CS1591
        [EnumMember(Value = "personal")]
        #pragma warning disable CS1591
        Personal,
        #pragma warning restore CS1591
    }
}
