// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ObservationEventInput : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action id that this observation is responding to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionId { get; set; }
#nullable restore
#else
        public string ActionId { get; set; }
#endif
        /// <summary>Unique event id (ULID/UUID)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The kind property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Models.ObservationEventInput_kind? Kind { get; set; }
        /// <summary>The observation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ObservationInput? Observation { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ObservationInput Observation { get; set; }
#endif
        /// <summary>The source property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Models.ObservationEventInput_source? Source { get; set; }
        /// <summary>Event timestamp</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timestamp { get; set; }
#nullable restore
#else
        public string Timestamp { get; set; }
#endif
        /// <summary>The tool call id that this observation is responding to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToolCallId { get; set; }
#nullable restore
#else
        public string ToolCallId { get; set; }
#endif
        /// <summary>The tool name that this observation is responding to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToolName { get; set; }
#nullable restore
#else
        public string ToolName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ObservationEventInput"/> and sets the default values.
        /// </summary>
        public ObservationEventInput()
        {
            Source = global::Soenneker.OpenHands.OpenApiClient.Models.ObservationEventInput_source.Environment;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ObservationEventInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.ObservationEventInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.ObservationEventInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action_id", n => { ActionId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.ObservationEventInput_kind>(); } },
                { "observation", n => { Observation = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ObservationInput>(global::Soenneker.OpenHands.OpenApiClient.Models.ObservationInput.CreateFromDiscriminatorValue); } },
                { "source", n => { Source = n.GetEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.ObservationEventInput_source>(); } },
                { "timestamp", n => { Timestamp = n.GetStringValue(); } },
                { "tool_call_id", n => { ToolCallId = n.GetStringValue(); } },
                { "tool_name", n => { ToolName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action_id", ActionId);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.ObservationEventInput_kind>("kind", Kind);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ObservationInput>("observation", Observation);
            writer.WriteEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.ObservationEventInput_source>("source", Source);
            writer.WriteStringValue("timestamp", Timestamp);
            writer.WriteStringValue("tool_call_id", ToolCallId);
            writer.WriteStringValue("tool_name", ToolName);
        }
    }
}
#pragma warning restore CS0618
