// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// ``agent_kind=&quot;openhands&quot;`` profile — references an LLM profile by name.Mirrors the configurable surface of:class:`~openhands.sdk.settings.model.OpenHandsAgentSettings`, except theconcrete ``llm`` is replaced by :attr:`llm_profile_ref` (resolved againstthe LLM profile store) and ``mcp_config`` by the inherited:attr:`~AgentProfileBase.mcp_server_refs`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OpenHandsAgentProfile : IParsable
    {
        /// <summary>Agent class to build.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Agent { get; set; }
#nullable restore
#else
        public string Agent { get; set; }
#endif
        /// <summary>Discriminator for the ``AgentProfile`` union. ``&apos;openhands&apos;`` selects the standard built-in OpenHands agent.</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfile_agent_kind? AgentKind { get; set; }
        /// <summary>Condenser settings for the agent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileCondenser? Condenser { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileCondenser Condenser { get; set; }
#endif
        /// <summary>&quot;Names of server-discovered skills to EXCLUDE from this agent&apos;s prompt — a deny-list over the discovered catalog. [] (the default) = all discovered skills; a listed name that is absent from the catalog is simply a no-op, so the field never fails a launch when the catalog drifts. Replaces the former allow-list ``skill_refs`` (#4017): skills are discovered from many incomplete sources, so exclusion is the only selection model that can&apos;t dangle.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DisabledSkills { get; set; }
#nullable restore
#else
        public List<string> DisabledSkills { get; set; }
#endif
        /// <summary>Enable sub-agent delegation via TaskToolSet.</summary>
        public bool? EnableSubAgents { get; set; }
        /// <summary>Enable the built-in switch_llm tool for switching between saved LLM profiles. Defaults True to match the global agent settings default (AgentSettingsConfig.enable_switch_llm_tool).</summary>
        public bool? EnableSwitchLlmTool { get; set; }
        /// <summary>Stable provenance handle for this profile. Conversations record this UUID; it never changes, even when the profile is renamed.</summary>
        public Guid? Id { get; set; }
        /// <summary>Name of the saved LLM profile to resolve for this agent. The profile itself stores no LLM credential — it lives on the referenced LLM profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LlmProfileRef { get; set; }
#nullable restore
#else
        public string LlmProfileRef { get; set; }
#endif
        /// <summary>Which of the user&apos;s globally configured MCP servers to expose. null = all; [] = none; a non-null list = filter to the named keys.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileMcpServerRefs? McpServerRefs { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileMcpServerRefs McpServerRefs { get; set; }
#endif
        /// <summary>Human-facing, renameable key shown in the profile picker.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Monotonic revision counter, bumped on each saved edit.</summary>
        public int? Revision { get; set; }
        /// <summary>The schema_version property</summary>
        public int? SchemaVersion { get; set; }
        /// <summary>Optional suffix appended to the system prompt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SystemMessageSuffix { get; set; }
#nullable restore
#else
        public string SystemMessageSuffix { get; set; }
#endif
        /// <summary>Maximum number of tool calls to execute concurrently per agent step. 1 = sequential (default).</summary>
        public int? ToolConcurrencyLimit { get; set; }
        /// <summary>Tool selection for the resolved agent. None (the default) = the server&apos;s standard tool set; [] = an explicitly bare agent; a non-empty list is used exactly as given.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileTools? Tools { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileTools Tools { get; set; }
#endif
        /// <summary>&quot;Secret-free critic/refinement policy for a profile.The non-credential subset of:class:`~openhands.sdk.settings.model.VerificationSettings`: ``critic_api_key``is omitted so the profile holds no secret. The critic reuses the resolvedLLM profile&apos;s key (the existing ``critic_api_key=None`` behavior).&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ProfileVerificationSettings? Verification { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ProfileVerificationSettings Verification { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfile"/> and sets the default values.
        /// </summary>
        public OpenHandsAgentProfile()
        {
            Agent = "CodeActAgent";
            EnableSubAgents = false;
            EnableSwitchLlmTool = true;
            Revision = 0;
            SchemaVersion = 1;
            ToolConcurrencyLimit = 1;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfile"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfile CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfile();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent", n => { Agent = n.GetStringValue(); } },
                { "agent_kind", n => { AgentKind = n.GetEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfile_agent_kind>(); } },
                { "condenser", n => { Condenser = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileCondenser>(global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileCondenser.CreateFromDiscriminatorValue); } },
                { "disabled_skills", n => { DisabledSkills = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "enable_sub_agents", n => { EnableSubAgents = n.GetBoolValue(); } },
                { "enable_switch_llm_tool", n => { EnableSwitchLlmTool = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "llm_profile_ref", n => { LlmProfileRef = n.GetStringValue(); } },
                { "mcp_server_refs", n => { McpServerRefs = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileMcpServerRefs>(global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileMcpServerRefs.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "revision", n => { Revision = n.GetIntValue(); } },
                { "schema_version", n => { SchemaVersion = n.GetIntValue(); } },
                { "system_message_suffix", n => { SystemMessageSuffix = n.GetStringValue(); } },
                { "tool_concurrency_limit", n => { ToolConcurrencyLimit = n.GetIntValue(); } },
                { "tools", n => { Tools = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileTools>(global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileTools.CreateFromDiscriminatorValue); } },
                { "verification", n => { Verification = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ProfileVerificationSettings>(global::Soenneker.OpenHands.OpenApiClient.Models.ProfileVerificationSettings.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("agent", Agent);
            writer.WriteEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfile_agent_kind>("agent_kind", AgentKind);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileCondenser>("condenser", Condenser);
            writer.WriteCollectionOfPrimitiveValues<string>("disabled_skills", DisabledSkills);
            writer.WriteBoolValue("enable_sub_agents", EnableSubAgents);
            writer.WriteBoolValue("enable_switch_llm_tool", EnableSwitchLlmTool);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("llm_profile_ref", LlmProfileRef);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileMcpServerRefs>("mcp_server_refs", McpServerRefs);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("revision", Revision);
            writer.WriteIntValue("schema_version", SchemaVersion);
            writer.WriteStringValue("system_message_suffix", SystemMessageSuffix);
            writer.WriteIntValue("tool_concurrency_limit", ToolConcurrencyLimit);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.OpenHandsAgentProfileTools>("tools", Tools);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ProfileVerificationSettings>("verification", Verification);
        }
    }
}
#pragma warning restore CS0618
