// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// Response model for organization app settings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrgAppSettingsResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The enable_proactive_conversation_starters property</summary>
        public bool? EnableProactiveConversationStarters { get; set; }
        /// <summary>The max_budget_per_task property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse.OrgAppSettingsResponse_max_budget_per_task? MaxBudgetPerTask { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse.OrgAppSettingsResponse_max_budget_per_task MaxBudgetPerTask { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse"/> and sets the default values.
        /// </summary>
        public OrgAppSettingsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enable_proactive_conversation_starters", n => { EnableProactiveConversationStarters = n.GetBoolValue(); } },
                { "max_budget_per_task", n => { MaxBudgetPerTask = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse.OrgAppSettingsResponse_max_budget_per_task>(global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse.OrgAppSettingsResponse_max_budget_per_task.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enable_proactive_conversation_starters", EnableProactiveConversationStarters);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse.OrgAppSettingsResponse_max_budget_per_task>("max_budget_per_task", MaxBudgetPerTask);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse_max_budget_per_taskMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrgAppSettingsResponse_max_budget_per_task : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse_max_budget_per_taskMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse_max_budget_per_taskMember1? OrgAppSettingsResponseMaxBudgetPerTaskMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse_max_budget_per_taskMember1 OrgAppSettingsResponseMaxBudgetPerTaskMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse.OrgAppSettingsResponse_max_budget_per_task"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse.OrgAppSettingsResponse_max_budget_per_task CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse.OrgAppSettingsResponse_max_budget_per_task();
                if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else {
                    result.OrgAppSettingsResponseMaxBudgetPerTaskMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse_max_budget_per_taskMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OrgAppSettingsResponseMaxBudgetPerTaskMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OrgAppSettingsResponseMaxBudgetPerTaskMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.OrgAppSettingsResponse_max_budget_per_taskMember1>(null, OrgAppSettingsResponseMaxBudgetPerTaskMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
