// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ProfileVerificationSettingsCriticMode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "finish_and_message")]
        #pragma warning disable CS1591
        FinishAndMessage,
        #pragma warning restore CS1591
        [EnumMember(Value = "all_actions")]
        #pragma warning disable CS1591
        AllActions,
        #pragma warning restore CS1591
    }
}
