// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ReadFileToolInput_kind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ReadFileTool")]
        #pragma warning disable CS1591
        ReadFileTool,
        #pragma warning restore CS1591
    }
}
