// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// Observation from reading a file.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReadFileObservationOutput : IParsable
    {
        /// <summary>Content returned from the tool as a list of TextContent/ImageContent objects. When there is an error, it should be written in this field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_content>? Content { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_content> Content { get; set; }
#endif
        /// <summary>The content read from the file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileContent { get; set; }
#nullable restore
#else
        public string FileContent { get; set; }
#endif
        /// <summary>The file path that was read.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FilePath { get; set; }
#nullable restore
#else
        public string FilePath { get; set; }
#endif
        /// <summary>Whether the observation indicates an error</summary>
        public bool? IsError { get; set; }
        /// <summary>Whether the content was truncated due to size limits.</summary>
        public bool? IsTruncated { get; set; }
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kind { get; set; }
#nullable restore
#else
        public string Kind { get; set; }
#endif
        /// <summary>If truncated, the range of lines shown (start, end) - 1-indexed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_lines_shown? LinesShown { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_lines_shown LinesShown { get; set; }
#endif
        /// <summary>Total number of lines in the file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_total_lines? TotalLines { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_total_lines TotalLines { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content", n => { Content = n.GetCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_content>(global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_content.CreateFromDiscriminatorValue)?.AsList(); } },
                { "file_content", n => { FileContent = n.GetStringValue(); } },
                { "file_path", n => { FilePath = n.GetStringValue(); } },
                { "is_error", n => { IsError = n.GetBoolValue(); } },
                { "is_truncated", n => { IsTruncated = n.GetBoolValue(); } },
                { "kind", n => { Kind = n.GetStringValue(); } },
                { "lines_shown", n => { LinesShown = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_lines_shown>(global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_lines_shown.CreateFromDiscriminatorValue); } },
                { "total_lines", n => { TotalLines = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_total_lines>(global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_total_lines.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_content>("content", Content);
            writer.WriteStringValue("file_content", FileContent);
            writer.WriteStringValue("file_path", FilePath);
            writer.WriteBoolValue("is_error", IsError);
            writer.WriteBoolValue("is_truncated", IsTruncated);
            writer.WriteStringValue("kind", Kind);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_lines_shown>("lines_shown", LinesShown);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_total_lines>("total_lines", TotalLines);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent"/>, <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TextContent"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReadFileObservationOutput_content : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent? ImageContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent ImageContent { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.TextContent? TextContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.TextContent TextContent { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_content"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_content CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_content();
                result.ImageContent = new global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent();
                result.TextContent = new global::Soenneker.OpenHands.OpenApiClient.Models.TextContent();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ImageContent != null || TextContent != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ImageContent, TextContent);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent>(null, ImageContent, TextContent);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_lines_shownMember1"/>, <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_lines_shownMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReadFileObservationOutput_lines_shown : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_lines_shownMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_lines_shownMember1? ReadFileObservationOutputLinesShownMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_lines_shownMember1 ReadFileObservationOutputLinesShownMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_lines_shownMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_lines_shownMember2? ReadFileObservationOutputLinesShownMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_lines_shownMember2 ReadFileObservationOutputLinesShownMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_lines_shown"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_lines_shown CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_lines_shown();
                result.ReadFileObservationOutputLinesShownMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_lines_shownMember1();
                result.ReadFileObservationOutputLinesShownMember2 = new global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_lines_shownMember2();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ReadFileObservationOutputLinesShownMember1 != null || ReadFileObservationOutputLinesShownMember2 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ReadFileObservationOutputLinesShownMember1, ReadFileObservationOutputLinesShownMember2);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_lines_shownMember1>(null, ReadFileObservationOutputLinesShownMember1, ReadFileObservationOutputLinesShownMember2);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_total_linesMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReadFileObservationOutput_total_lines : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_total_linesMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_total_linesMember1? ReadFileObservationOutputTotalLinesMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_total_linesMember1 ReadFileObservationOutputTotalLinesMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_total_lines"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_total_lines CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput.ReadFileObservationOutput_total_lines();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.ReadFileObservationOutputTotalLinesMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_total_linesMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ReadFileObservationOutputTotalLinesMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ReadFileObservationOutputTotalLinesMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ReadFileObservationOutput_total_linesMember1>(null, ReadFileObservationOutputTotalLinesMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
