// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SandboxStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "STARTING")]
        #pragma warning disable CS1591
        STARTING,
        #pragma warning restore CS1591
        [EnumMember(Value = "RUNNING")]
        #pragma warning disable CS1591
        RUNNING,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAUSED")]
        #pragma warning disable CS1591
        PAUSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "MISSING")]
        #pragma warning disable CS1591
        MISSING,
        #pragma warning restore CS1591
    }
}
