// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>LLM API endpoint mode. &apos;auto&apos; resolves from model metadata and SDK fallbacks; use &apos;chat&apos; or &apos;responses&apos; to override endpoint selection for proxy aliases and newly released models.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StrictLlmApiMode
    {
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "chat")]
        #pragma warning disable CS1591
        Chat,
        #pragma warning restore CS1591
        [EnumMember(Value = "responses")]
        #pragma warning disable CS1591
        Responses,
        #pragma warning restore CS1591
    }
}
