// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>&quot;The command that was executed: \&quot;view\&quot; or \&quot;plan\&quot;.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TaskTrackerObservationOutputCommand
    {
        [EnumMember(Value = "view")]
        #pragma warning disable CS1591
        View,
        #pragma warning restore CS1591
        [EnumMember(Value = "plan")]
        #pragma warning disable CS1591
        Plan,
        #pragma warning restore CS1591
    }
}
