// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// A ToolResult that can be rendered as a CLI output.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TerminalObservationInput : IParsable
    {
        /// <summary>The shell command that was executed. Can be empty string if the observation is from a previous command that hit soft timeout and is not yet finished.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_command? Command { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_command Command { get; set; }
#endif
        /// <summary>Content returned from the tool as a list of TextContent/ImageContent objects. When there is an error, it should be written in this field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_content>? Content { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_content> Content { get; set; }
#endif
        /// <summary>The exit code of the command. -1 indicates the process hit the soft timeout and is not yet finished.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_exit_code? ExitCode { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_exit_code ExitCode { get; set; }
#endif
        /// <summary>Directory where full output files are saved</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_full_output_save_dir? FullOutputSaveDir { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_full_output_save_dir FullOutputSaveDir { get; set; }
#endif
        /// <summary>Whether the observation indicates an error</summary>
        public bool? IsError { get; set; }
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kind { get; set; }
#nullable restore
#else
        public string Kind { get; set; }
#endif
        /// <summary>Additional metadata captured from PS1 after command execution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.CmdOutputMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.CmdOutputMetadata Metadata { get; set; }
#endif
        /// <summary>Whether the command execution timed out.</summary>
        public bool? Timeout { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "command", n => { Command = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_command>(global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_command.CreateFromDiscriminatorValue); } },
                { "content", n => { Content = n.GetCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_content>(global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_content.CreateFromDiscriminatorValue)?.AsList(); } },
                { "exit_code", n => { ExitCode = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_exit_code>(global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_exit_code.CreateFromDiscriminatorValue); } },
                { "full_output_save_dir", n => { FullOutputSaveDir = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_full_output_save_dir>(global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_full_output_save_dir.CreateFromDiscriminatorValue); } },
                { "is_error", n => { IsError = n.GetBoolValue(); } },
                { "kind", n => { Kind = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.CmdOutputMetadata>(global::Soenneker.OpenHands.OpenApiClient.Models.CmdOutputMetadata.CreateFromDiscriminatorValue); } },
                { "timeout", n => { Timeout = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_command>("command", Command);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_content>("content", Content);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_exit_code>("exit_code", ExitCode);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_full_output_save_dir>("full_output_save_dir", FullOutputSaveDir);
            writer.WriteBoolValue("is_error", IsError);
            writer.WriteStringValue("kind", Kind);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.CmdOutputMetadata>("metadata", Metadata);
            writer.WriteBoolValue("timeout", Timeout);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_commandMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TerminalObservationInput_command : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_commandMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_commandMember1? TerminalObservationInputCommandMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_commandMember1 TerminalObservationInputCommandMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_command"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_command CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_command();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.TerminalObservationInputCommandMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_commandMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(TerminalObservationInputCommandMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(TerminalObservationInputCommandMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_commandMember1>(null, TerminalObservationInputCommandMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent"/>, <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TextContent"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TerminalObservationInput_content : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent? ImageContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent ImageContent { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.TextContent? TextContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.TextContent TextContent { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_content"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_content CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_content();
                result.ImageContent = new global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent();
                result.TextContent = new global::Soenneker.OpenHands.OpenApiClient.Models.TextContent();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ImageContent != null || TextContent != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ImageContent, TextContent);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent>(null, ImageContent, TextContent);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_exit_codeMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TerminalObservationInput_exit_code : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_exit_codeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_exit_codeMember1? TerminalObservationInputExitCodeMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_exit_codeMember1 TerminalObservationInputExitCodeMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_exit_code"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_exit_code CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_exit_code();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.TerminalObservationInputExitCodeMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_exit_codeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(TerminalObservationInputExitCodeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(TerminalObservationInputExitCodeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_exit_codeMember1>(null, TerminalObservationInputExitCodeMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_full_output_save_dirMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TerminalObservationInput_full_output_save_dir : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_full_output_save_dirMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_full_output_save_dirMember1? TerminalObservationInputFullOutputSaveDirMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_full_output_save_dirMember1 TerminalObservationInputFullOutputSaveDirMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_full_output_save_dir"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_full_output_save_dir CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput.TerminalObservationInput_full_output_save_dir();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.TerminalObservationInputFullOutputSaveDirMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_full_output_save_dirMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(TerminalObservationInputFullOutputSaveDirMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(TerminalObservationInputFullOutputSaveDirMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.TerminalObservationInput_full_output_save_dirMember1>(null, TerminalObservationInputFullOutputSaveDirMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
