// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// Response model for user app settings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserAppSettingsResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The enable_sound_notifications property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_enable_sound_notifications? EnableSoundNotifications { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_enable_sound_notifications EnableSoundNotifications { get; set; }
#endif
        /// <summary>The git_user_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_email? GitUserEmail { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_email GitUserEmail { get; set; }
#endif
        /// <summary>The git_user_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_name? GitUserName { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_name GitUserName { get; set; }
#endif
        /// <summary>The language property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_language? Language { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_language Language { get; set; }
#endif
        /// <summary>The user_consents_to_analytics property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_user_consents_to_analytics? UserConsentsToAnalytics { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_user_consents_to_analytics UserConsentsToAnalytics { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse"/> and sets the default values.
        /// </summary>
        public UserAppSettingsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enable_sound_notifications", n => { EnableSoundNotifications = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_enable_sound_notifications>(global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_enable_sound_notifications.CreateFromDiscriminatorValue); } },
                { "git_user_email", n => { GitUserEmail = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_email>(global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_email.CreateFromDiscriminatorValue); } },
                { "git_user_name", n => { GitUserName = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_name>(global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_name.CreateFromDiscriminatorValue); } },
                { "language", n => { Language = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_language>(global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_language.CreateFromDiscriminatorValue); } },
                { "user_consents_to_analytics", n => { UserConsentsToAnalytics = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_user_consents_to_analytics>(global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_user_consents_to_analytics.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_enable_sound_notifications>("enable_sound_notifications", EnableSoundNotifications);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_email>("git_user_email", GitUserEmail);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_name>("git_user_name", GitUserName);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_language>("language", Language);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_user_consents_to_analytics>("user_consents_to_analytics", UserConsentsToAnalytics);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_enable_sound_notificationsMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UserAppSettingsResponse_enable_sound_notifications : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_enable_sound_notificationsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_enable_sound_notificationsMember1? UserAppSettingsResponseEnableSoundNotificationsMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_enable_sound_notificationsMember1 UserAppSettingsResponseEnableSoundNotificationsMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_enable_sound_notifications"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_enable_sound_notifications CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_enable_sound_notifications();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.UserAppSettingsResponseEnableSoundNotificationsMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_enable_sound_notificationsMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UserAppSettingsResponseEnableSoundNotificationsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UserAppSettingsResponseEnableSoundNotificationsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_enable_sound_notificationsMember1>(null, UserAppSettingsResponseEnableSoundNotificationsMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_git_user_emailMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UserAppSettingsResponse_git_user_email : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_git_user_emailMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_git_user_emailMember1? UserAppSettingsResponseGitUserEmailMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_git_user_emailMember1 UserAppSettingsResponseGitUserEmailMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_email"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_email CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_email();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.UserAppSettingsResponseGitUserEmailMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_git_user_emailMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UserAppSettingsResponseGitUserEmailMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UserAppSettingsResponseGitUserEmailMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_git_user_emailMember1>(null, UserAppSettingsResponseGitUserEmailMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_git_user_nameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UserAppSettingsResponse_git_user_name : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_git_user_nameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_git_user_nameMember1? UserAppSettingsResponseGitUserNameMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_git_user_nameMember1 UserAppSettingsResponseGitUserNameMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_name"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_name CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_git_user_name();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.UserAppSettingsResponseGitUserNameMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_git_user_nameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UserAppSettingsResponseGitUserNameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UserAppSettingsResponseGitUserNameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_git_user_nameMember1>(null, UserAppSettingsResponseGitUserNameMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_languageMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UserAppSettingsResponse_language : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_languageMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_languageMember1? UserAppSettingsResponseLanguageMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_languageMember1 UserAppSettingsResponseLanguageMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_language"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_language CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_language();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.UserAppSettingsResponseLanguageMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_languageMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UserAppSettingsResponseLanguageMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UserAppSettingsResponseLanguageMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_languageMember1>(null, UserAppSettingsResponseLanguageMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_user_consents_to_analyticsMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UserAppSettingsResponse_user_consents_to_analytics : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_user_consents_to_analyticsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_user_consents_to_analyticsMember1? UserAppSettingsResponseUserConsentsToAnalyticsMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_user_consents_to_analyticsMember1 UserAppSettingsResponseUserConsentsToAnalyticsMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_user_consents_to_analytics"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_user_consents_to_analytics CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse.UserAppSettingsResponse_user_consents_to_analytics();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.UserAppSettingsResponseUserConsentsToAnalyticsMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_user_consents_to_analyticsMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UserAppSettingsResponseUserConsentsToAnalyticsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UserAppSettingsResponseUserConsentsToAnalyticsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.UserAppSettingsResponse_user_consents_to_analyticsMember1>(null, UserAppSettingsResponseUserConsentsToAnalyticsMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
