// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// Observation returned after a vision model inspects an image.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VisionInspectObservationInput : IParsable
    {
        /// <summary>Text answer returned by the vision model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Answer { get; set; }
#nullable restore
#else
        public string Answer { get; set; }
#endif
        /// <summary>Vision-capable LLM endpoint used for inspection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseUrl { get; set; }
#nullable restore
#else
        public string BaseUrl { get; set; }
#endif
        /// <summary>Content returned from the tool as a list of TextContent/ImageContent objects. When there is an error, it should be written in this field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.VisionInspectObservationInputContentItem>? Content { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.VisionInspectObservationInputContentItem> Content { get; set; }
#endif
        /// <summary>Image index that was inspected.</summary>
        public int? ImageIndex { get; set; }
        /// <summary>Whether the observation indicates an error</summary>
        public bool? IsError { get; set; }
        /// <summary>The kind property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Models.VisionInspectObservationInput_kind? Kind { get; set; }
        /// <summary>Vision-capable model used for inspection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>Vision-capable profile used for inspection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileName { get; set; }
#nullable restore
#else
        public string ProfileName { get; set; }
#endif
        /// <summary>Question asked of the vision model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Question { get; set; }
#nullable restore
#else
        public string Question { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.VisionInspectObservationInput"/> and sets the default values.
        /// </summary>
        public VisionInspectObservationInput()
        {
            IsError = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.VisionInspectObservationInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.VisionInspectObservationInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.VisionInspectObservationInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "answer", n => { Answer = n.GetStringValue(); } },
                { "base_url", n => { BaseUrl = n.GetStringValue(); } },
                { "content", n => { Content = n.GetCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.VisionInspectObservationInputContentItem>(global::Soenneker.OpenHands.OpenApiClient.Models.VisionInspectObservationInputContentItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "image_index", n => { ImageIndex = n.GetIntValue(); } },
                { "is_error", n => { IsError = n.GetBoolValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.VisionInspectObservationInput_kind>(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "profile_name", n => { ProfileName = n.GetStringValue(); } },
                { "question", n => { Question = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("answer", Answer);
            writer.WriteStringValue("base_url", BaseUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.VisionInspectObservationInputContentItem>("content", Content);
            writer.WriteIntValue("image_index", ImageIndex);
            writer.WriteBoolValue("is_error", IsError);
            writer.WriteEnumValue<global::Soenneker.OpenHands.OpenApiClient.Models.VisionInspectObservationInput_kind>("kind", Kind);
            writer.WriteStringValue("model", Model);
            writer.WriteStringValue("profile_name", ProfileName);
            writer.WriteStringValue("question", Question);
        }
    }
}
#pragma warning restore CS0618
