// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Models
{
    /// <summary>
    /// Observation from writing a file.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WriteFileObservationInput : IParsable
    {
        /// <summary>Content returned from the tool as a list of TextContent/ImageContent objects. When there is an error, it should be written in this field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_content>? Content { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_content> Content { get; set; }
#endif
        /// <summary>The file path that was written.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_file_path? FilePath { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_file_path FilePath { get; set; }
#endif
        /// <summary>Whether the observation indicates an error</summary>
        public bool? IsError { get; set; }
        /// <summary>Whether a new file was created.</summary>
        public bool? IsNewFile { get; set; }
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kind { get; set; }
#nullable restore
#else
        public string Kind { get; set; }
#endif
        /// <summary>The new content written to the file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_new_content? NewContent { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_new_content NewContent { get; set; }
#endif
        /// <summary>The previous content of the file (if it existed).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_old_content? OldContent { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_old_content OldContent { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content", n => { Content = n.GetCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_content>(global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_content.CreateFromDiscriminatorValue)?.AsList(); } },
                { "file_path", n => { FilePath = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_file_path>(global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_file_path.CreateFromDiscriminatorValue); } },
                { "is_error", n => { IsError = n.GetBoolValue(); } },
                { "is_new_file", n => { IsNewFile = n.GetBoolValue(); } },
                { "kind", n => { Kind = n.GetStringValue(); } },
                { "new_content", n => { NewContent = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_new_content>(global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_new_content.CreateFromDiscriminatorValue); } },
                { "old_content", n => { OldContent = n.GetObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_old_content>(global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_old_content.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_content>("content", Content);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_file_path>("file_path", FilePath);
            writer.WriteBoolValue("is_error", IsError);
            writer.WriteBoolValue("is_new_file", IsNewFile);
            writer.WriteStringValue("kind", Kind);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_new_content>("new_content", NewContent);
            writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_old_content>("old_content", OldContent);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent"/>, <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TextContent"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WriteFileObservationInput_content : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent? ImageContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent ImageContent { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.TextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.TextContent? TextContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.TextContent TextContent { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_content"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_content CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_content();
                result.ImageContent = new global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent();
                result.TextContent = new global::Soenneker.OpenHands.OpenApiClient.Models.TextContent();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ImageContent != null || TextContent != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ImageContent, TextContent);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.ImageContent>(null, ImageContent, TextContent);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_file_pathMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WriteFileObservationInput_file_path : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_file_pathMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_file_pathMember1? WriteFileObservationInputFilePathMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_file_pathMember1 WriteFileObservationInputFilePathMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_file_path"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_file_path CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_file_path();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.WriteFileObservationInputFilePathMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_file_pathMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WriteFileObservationInputFilePathMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WriteFileObservationInputFilePathMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_file_pathMember1>(null, WriteFileObservationInputFilePathMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_new_contentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WriteFileObservationInput_new_content : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_new_contentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_new_contentMember1? WriteFileObservationInputNewContentMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_new_contentMember1 WriteFileObservationInputNewContentMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_new_content"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_new_content CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_new_content();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.WriteFileObservationInputNewContentMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_new_contentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WriteFileObservationInputNewContentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WriteFileObservationInputNewContentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_new_contentMember1>(null, WriteFileObservationInputNewContentMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_old_contentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WriteFileObservationInput_old_content : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_old_contentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_old_contentMember1? WriteFileObservationInputOldContentMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_old_contentMember1 WriteFileObservationInputOldContentMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_old_content"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_old_content CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput.WriteFileObservationInput_old_content();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.WriteFileObservationInputOldContentMember1 = new global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_old_contentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WriteFileObservationInputOldContentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WriteFileObservationInputOldContentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.OpenHands.OpenApiClient.Models.WriteFileObservationInput_old_contentMember1>(null, WriteFileObservationInputOldContentMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
