// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenHands.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm
{
    /// <summary>
    /// Builds and executes requests for operations under \api\organizations\llm
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LlmRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm.LlmRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LlmRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/organizations/llm{?org_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm.LlmRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LlmRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/organizations/llm{?org_id*}", rawUrl)
        {
        }
        /// <summary>
        /// Get org-default settings through the deprecated ``/llm`` wrapper.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.OrgDefaultsSettingsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.OpenHands.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenHands.OpenApiClient.Models.OrgDefaultsSettingsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm.LlmRequestBuilder.LlmRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenHands.OpenApiClient.Models.OrgDefaultsSettingsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm.LlmRequestBuilder.LlmRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.OpenHands.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.OpenHands.OpenApiClient.Models.OrgDefaultsSettingsResponse>(requestInfo, global::Soenneker.OpenHands.OpenApiClient.Models.OrgDefaultsSettingsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update org-default settings through the deprecated ``/llm`` wrapper.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Models.OrgDefaultsSettingsResponse"/></returns>
        /// <param name="body">Request model for updating an organization.``agent_settings_diff`` and ``conversation_settings_diff`` are sparse diffsthat are deep-merged into the org row and then validated as full settingsbefore persistence.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.OpenHands.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenHands.OpenApiClient.Models.OrgDefaultsSettingsResponse?> PostAsync(global::Soenneker.OpenHands.OpenApiClient.Models.OrgUpdate body, Action<RequestConfiguration<global::Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm.LlmRequestBuilder.LlmRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenHands.OpenApiClient.Models.OrgDefaultsSettingsResponse> PostAsync(global::Soenneker.OpenHands.OpenApiClient.Models.OrgUpdate body, Action<RequestConfiguration<global::Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm.LlmRequestBuilder.LlmRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.OpenHands.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.OpenHands.OpenApiClient.Models.OrgDefaultsSettingsResponse>(requestInfo, global::Soenneker.OpenHands.OpenApiClient.Models.OrgDefaultsSettingsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get org-default settings through the deprecated ``/llm`` wrapper.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm.LlmRequestBuilder.LlmRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm.LlmRequestBuilder.LlmRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update org-default settings through the deprecated ``/llm`` wrapper.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request model for updating an organization.``agent_settings_diff`` and ``conversation_settings_diff`` are sparse diffsthat are deep-merged into the org row and then validated as full settingsbefore persistence.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.OpenHands.OpenApiClient.Models.OrgUpdate body, Action<RequestConfiguration<global::Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm.LlmRequestBuilder.LlmRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.OpenHands.OpenApiClient.Models.OrgUpdate body, Action<RequestConfiguration<global::Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm.LlmRequestBuilder.LlmRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm.LlmRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        [Obsolete("")]
        public global::Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm.LlmRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.OpenHands.OpenApiClient.Api.Organizations.Llm.LlmRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get org-default settings through the deprecated ``/llm`` wrapper.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LlmRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("org_id")]
            public string? OrgId { get; set; }
#nullable restore
#else
            [QueryParameter("org_id")]
            public string OrgId { get; set; }
#endif
        }
        /// <summary>
        /// Update org-default settings through the deprecated ``/llm`` wrapper.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LlmRequestBuilderPostQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("org_id")]
            public string? OrgId { get; set; }
#nullable restore
#else
            [QueryParameter("org_id")]
            public string OrgId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
