// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenHands.OpenApiClient.Oauth.Keycloak.Offline.Callback;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenHands.OpenApiClient.Oauth.Keycloak.Offline
{
    /// <summary>
    /// Builds and executes requests for operations under \oauth\keycloak\offline
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OfflineRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The callback property</summary>
        public global::Soenneker.OpenHands.OpenApiClient.Oauth.Keycloak.Offline.Callback.CallbackRequestBuilder Callback
        {
            get => new global::Soenneker.OpenHands.OpenApiClient.Oauth.Keycloak.Offline.Callback.CallbackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Oauth.Keycloak.Offline.OfflineRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OfflineRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/oauth/keycloak/offline", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenHands.OpenApiClient.Oauth.Keycloak.Offline.OfflineRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OfflineRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/oauth/keycloak/offline", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
